server:
  port: 9000
  servlet:
    context-path: /book

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /**
    
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  type-aliases-package: com.example.demo.common.entity
  global-config:
    banner: false
    db-config:
      id-type: auto
      select-strategy: ignored
      insert-strategy: ignored
      update-strategy: ignored
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  

